version: '2'

services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  pgdata:
    external: false
